### ISSUE TITLE
Current state - Mint 18

### ISSUE THREAD

**Issue by ShalokShalom** [ch1x0r/MintyFresh2016#2]
Will this work on 18?

**Comment by ghost** [comment]
Looking forward to know.

**Comment by ghost** [comment]
Or indeed Mint 19?

**Comment by mkwilbux** [comment]
I happen to be working on it now... Will let you know in a minute... or more.. but GUYzzzz I moved to gitlab

I need to update that too

**Comment by ch1x0r** [comment]
working on it...

**Comment by ch1x0r** [comment]
Done. Works.
